### ISSUE TITLE
Teacher training

### ISSUE THREAD

**Issue by shumink** [bhheo/AB_distillation#1]
Hi,

Your CIFAR 10 teacher has achieved 4.51% of error rate. May I know how do you achieve this? I'm working my ass off to tune the parameters only to get 88% :(. Can you please share some tips..

Thanks,
Shumin

**Comment by bhheo** [comment]
Hello,

Training settings in 'cifar10_AB_distillation.py' can achieve 4.51% or similar performance.

In 'cifar10_AB_distillation.py', change following lines.
```
Line 25 : distill_epoch = 0
Line 26 : max_epoch = 200

Line 30 : KD = False

Line 70 : s_net = WRN22_4()
```
Then, distillation parts will not be activated.
You can train WRN22_4 with similar performance of my teacher network.

Please check the code for detailed parameters.

**Comment by shumink** [comment]
Thanks!
