### ISSUE TITLE
Clarification in optimizer

### ISSUE THREAD

**Issue by krishnakanthnakka** [bhheo/AB_distillation#4]
https://github.com/bhheo/AB_distillation/blob/a7701d3506e13da87bda75aba1cee6397408144f/cifar10_AB_distillation.py#L232

Line 232, can you please tell if you are resetting the optimizer?  Do you intend to decrease the learning rate at this epoch?

**Comment by bhheo** [comment]
I don't want to resetting optimizer. but, that line is resetting the optimizer.
When I write down the code, I was not familiar with classification code.
So, it was a mistake.

Recently, I tested about changing learning rate without reset.
The result is almost same as original code.

**Comment by krishnakanthnakka** [comment]
Thank you. I'm closing the issue.
